const canvas=document.getElementById('stackCanvas'),ctx=canvas.getContext('2d'),area=document.getElementById('stackArea');
const $=id=>document.getElementById(id);let W,H,dpr,playing=false,score=0,level=1,stack=[],mover=null,last=0;
const colors=['#ff638f','#ffd84d','#48dfbd','#54bfff','#9a68ff','#ff8d4d'];
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=area.clientWidth;H=area.clientHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}
addEventListener('resize',resize);resize();
function reset(){score=0;level=1;stack=[];const baseW=Math.min(250,W*.48);stack.push({x:W/2-baseW/2,y:H-70,w:baseW,h:52,c:'#7055ef'});newMover();update()}
function newMover(){const prev=stack[stack.length-1],w=Math.max(70,prev.w-(level>2?2:0));mover={x:0,y:prev.y-58,w,h:52,c:colors[stack.length%colors.length],vx:(2.2+level*.18)*(Math.random()<.5?1:-1)};if(mover.vx<0)mover.x=W-w}
function drop(){if(!playing||!mover)return;const prev=stack[stack.length-1],left=Math.max(mover.x,prev.x),right=Math.min(mover.x+mover.w,prev.x+prev.w),overlap=right-left;if(overlap<=10){gameOver();return}
const centerDiff=Math.abs((mover.x+mover.w/2)-(prev.x+prev.w/2));const perfect=centerDiff<9;let placed={x:left,y:mover.y,w:overlap,h:mover.h,c:mover.c};if(perfect){placed.x=prev.x;placed.w=prev.w;score+=25}else score+=Math.max(5,Math.round(15*overlap/prev.w));stack.push(placed);level=stack.length; if(placed.y<150){stack.forEach(s=>s.y+=58)} newMover();update()}
function update(){$('score').textContent=score;$('level').textContent=level;$('best').textContent=localStorage.ssBest||0}
function gameOver(){playing=false;localStorage.ssBest=Math.max(+localStorage.ssBest||0,score);update();$('final').textContent=`Score ${score} • ${stack.length-1} squishies stacked.`;$('over').classList.remove('hidden')}
function roundRect(x,y,w,h,r,c){ctx.fillStyle=c;ctx.beginPath();ctx.roundRect(x,y,w,h,[r,r,r*.8,r*.8]);ctx.fill();ctx.fillStyle='#252641';ctx.beginPath();ctx.arc(x+w*.37,y+h*.43,3.5,0,7);ctx.arc(x+w*.63,y+h*.43,3.5,0,7);ctx.fill();ctx.beginPath();ctx.arc(x+w*.5,y+h*.56,7,0,Math.PI);ctx.strokeStyle='#252641';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#ffffff66';ctx.beginPath();ctx.ellipse(x+w*.22,y+h*.2,w*.09,h*.09,-.4,0,7);ctx.fill()}
function loop(t){const dt=Math.min(2,(t-last)/16.67||1);last=t;if(playing&&mover){mover.x+=mover.vx*dt;if(mover.x<=0||mover.x+mover.w>=W){mover.vx*=-1;mover.x=Math.max(0,Math.min(W-mover.w,mover.x))}}ctx.clearRect(0,0,W,H);stack.forEach(s=>roundRect(s.x,s.y,s.w,s.h,18,s.c));if(mover)roundRect(mover.x,mover.y,mover.w,mover.h,18,mover.c);requestAnimationFrame(loop)}requestAnimationFrame(loop);
function start(){reset();playing=true;$('start').classList.add('hidden');$('over').classList.add('hidden')}
$('startBtn').onclick=start;$('again').onclick=start;area.addEventListener('pointerdown',e=>{if(e.target.tagName!=='BUTTON')drop()});